version: '3'
services:
  file-uploader:
    build: .
    container_name: file_uploader_service
    ports:
      - "3026:3026"
    volumes:
      - file_uploads_data:/usr/src/app/uploads

volumes:
  file_uploads_data:
